---
- hosts: switches
  connection: local

  vars_files:
  - group_vars/all
  - group_vars/site1.yml

  vars:
    cli:
      host: "{{ device_ip }}"
      username: cisco
      password: cisco
      authorize: yes
      auth_pass: cisco
      transport: cli

  tasks:

  - name: Gather facts
    ios_facts:
      host: "{{ device_ip }}"
      provider: "{{ cli }}"
    register: result

  - debug: var=result

  - name: Configure device hostname
    ios_config:
      lines: hostname {{ item[switches].hostname }}
      provider: "{{ cli }}"
    with_items: switches

  - name: Service configuration
    ios_config:
      lines:
        - no service pad
        - service tcp-keepalives-in
        - service tcp-keepalives-out
        - service timestamps debug datetime msec localtime show-timezone
        - service timestamps log datetime msec localtime show-timezone
        - service password-encryption
        - service compress-config
        - service sequence-numbers
      provider: "{{ cli }}"

  - name: Domain Name
    ios_config:
      lines:
        - ip domain-name {{ domain_name }}
      provider: "{{ cli }}"

  - name: DNS Servers
    ios_config:
      lines:
        - ip name-server {{ dns_server1 }}
        - ip name-server {{ dns_server2 }}
      before:
        - no ip name-server
      provider: "{{ cli }}"

  - name: Logging
    ios_config:
      lines:
        - logging buffered 500000
        - logging rate-limit 10 except critical
      provider: "{{ cli }}"

# This section needs to be made idempotent, as currently, if you change the variable the device just appends additional Syslog servers

  - name: Syslog Server
    ios_config:
      lines:
        - logging host {{ syslog_server1 }}
      provider: "{{ cli }}"

